name: Flutter Build APK Test


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Configuro o java"
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.13.0‑0.3.pre'

      - name: Atualizo pacotes
        run: flutter pub get

      - name: Rodo o teste de unidade
        run: flutter test

      - name: Crio o apk
        run: flutter build apk --split-per-abi --release

      - name: Crio o bundle APPBUNDLE
        run: flutter build appbundle --release

      - name: Crio uma versão nova no repositório
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.RELEASES_TOKEN }}